nama = input("Nama                       : ")
NIM = input("NIM                        : ")
kelas = input("Kelas Paralel              : ")
ttl = input("Tempat/Tanggal Lahir       : ")
alamat = input("Alamat                     : ")
hobby = input("Hobby                      : ")
nohp = input("No. HP                     : \n\n")

print(f"Nama                       :  {nama}")
print(f"NIM                        :  {NIM}")
print(f"Kelas Paralel              :  {kelas}")
print(f"Tempat/Tanggal Lahir       :  {ttl}")
print(f"Alamat                     :  {alamat}")
print(f"Hobby                      :  {hobby}")
print(f"No. HP                     :  {nohp}")